INSERT INTO tag (name) VALUES ('CREATED'), ('WORKING'), ('COMPLETED');

INSERT INTO task(name,description,tag_id,created_at,updated_at) VALUES
('clean','remove all files generated by the previous build',1,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('validate','validate the project is correct and all necessary information is available',2,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('compile','compile the source code of the project',2,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('test','run tests using a suitable unit testing framework. These tests should not require the code be packaged or deployed',1,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('package','take the compiled code and package it in its distributable format, such as a JAR',1,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('verify','run any checks to verify the package is valid and meets quality criteria',1,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('install','install the package into the local repository, for use as a dependency in other projects locally',3,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('site','generate the project site documentation',3,'2023-01-20 16:00:00','2023-01-20 16:00:00'),
('deploy','done in an integration or release environment, copies the final package to the remote repository for sharing with other developers and projects',3,'2023-01-20 16:00:00','2023-01-20 16:00:00');

UPDATE task SET tag_id=2, updated_at='2023-01-20 16:00:00' WHERE id=1;
UPDATE task SET tag_id=3, updated_at='2023-01-20 16:00:00' WHERE id=2;
